codecov:
  token: 5fa0b012-6dc3-4c29-8d77-d2bffccf59a0
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...100"
  status:
    patch:
      default:
        enabled: no
    project:
      default:
        threshold: 1%
